services:

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    ports: [ '3306:3306' ]
    env_file: '.env'
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_ROOT_HOST: localhost
    volumes:
      - ./docker/data.local/mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '--silent']
      interval: 2s
      retries: 15

  server:
    container_name: server
    image: ghcr.io/wani4ka/yadisk
    ports: [ '80:80' ]
    env_file: '.env'
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      spring.jpa.hibernate.ddl-auto: update
      spring.datasource.url: 'jdbc:mysql://mariadb:3306/${MYSQL_DATABASE}'
      spring.datasource.username: '${MYSQL_USER}'
      spring.datasource.password: '${MYSQL_PASSWORD}'
      spring.datasource.driver-class-name: 'com.mysql.cj.jdbc.Driver'
      server.port: '80'
